# Generated by Django 4.2 on 2023-04-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PhoneNumber', models.IntegerField(max_length=12)),
                ('Image_URL', models.CharField(max_length=2083)),
            ],
        ),
    ]
