# Generated by Django 4.2 on 2023-04-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverDetails',
            new_name='Driver_Details',
        ),
    ]
