# Generated by Django 4.2 on 2023-04-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_details', '0002_rename_driverdetails_driver_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver_details',
            old_name='PhoneNumber',
            new_name='Phone_Number',
        ),
    ]
