# Generated by Django 4.2 on 2023-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_details', '0007_alter_driver_details_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_details',
            name='Driver_Pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
