# Generated by Django 4.2 on 2023-04-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_details', '0008_driver_details_driver_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_details',
            name='Image_URL',
        ),
    ]
