# Generated by Django 4.1.7 on 2023-04-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus1_lat", models.FloatField()),
                ("bus2_lon", models.FloatField()),
                ("bus3_lat", models.FloatField()),
                ("bus4_lon", models.FloatField()),
            ],
        ),
    ]
