# Generated by Django 4.1.7 on 2023-04-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locationdata",
            name="bus2_lon",
        ),
        migrations.AddField(
            model_name="locationdata",
            name="bus1_lng",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locationdata",
            name="bus2_lng",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locationdata",
            name="bus3_lng",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locationdata",
            name="bus4_lng",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
