# Generated by Django 4.1.7 on 2023-04-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0003_bus1_location_bus2_location_bus3_location_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bus2_Location",
            new_name="Bus1_data",
        ),
        migrations.RenameModel(
            old_name="Bus1_Location",
            new_name="Bus2_data",
        ),
        migrations.RenameModel(
            old_name="Bus3_Location",
            new_name="Bus3_data",
        ),
        migrations.RenameModel(
            old_name="Bus4_Location",
            new_name="Bus4_data",
        ),
        migrations.RenameField(
            model_name="bus1_data",
            old_name="bus2_date",
            new_name="bus1_date",
        ),
        migrations.RenameField(
            model_name="bus1_data",
            old_name="bus2_lat",
            new_name="bus1_lat",
        ),
        migrations.RenameField(
            model_name="bus1_data",
            old_name="bus2_lng",
            new_name="bus1_lng",
        ),
        migrations.RenameField(
            model_name="bus1_data",
            old_name="bus2_speed",
            new_name="bus1_speed",
        ),
        migrations.RenameField(
            model_name="bus1_data",
            old_name="bus2_time",
            new_name="bus1_time",
        ),
        migrations.RenameField(
            model_name="bus2_data",
            old_name="bus1_date",
            new_name="bus2_date",
        ),
        migrations.RenameField(
            model_name="bus2_data",
            old_name="bus1_lat",
            new_name="bus2_lat",
        ),
        migrations.RenameField(
            model_name="bus2_data",
            old_name="bus1_lng",
            new_name="bus2_lng",
        ),
        migrations.RenameField(
            model_name="bus2_data",
            old_name="bus1_speed",
            new_name="bus2_speed",
        ),
        migrations.RenameField(
            model_name="bus2_data",
            old_name="bus1_time",
            new_name="bus2_time",
        ),
    ]
